FROM apache/airflow:3.1.3

USER root

# Install Java 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow

# Install PySpark
RUN pip install --no-cache-dir pyspark

# Set default project base directory using the symlink
ENV PROJECT_BASE_DIR=/project