FROM apache/airflow:3.1.3

USER root

# Install Java 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Create project directory
RUN mkdir -p /project

USER airflow

# Install PySpark and Redis
RUN pip install --no-cache-dir pyspark redis

# Set default project base directory
ENV PROJECT_BASE_DIR=/project